version: '2'

services:
  nginx:
    image: 133506877714.dkr.ecr.eu-west-1.amazonaws.com/ztm-nginx:live
    ports:
      - 80:80
    volumes:
      - ./zendesk_tickets_machine/staticfiles:/static
    depends_on:
      - app

  app:
    image: 133506877714.dkr.ecr.eu-west-1.amazonaws.com/ztm-app:live
    volumes:
      - ./zendesk_tickets_machine/staticfiles:/app/zendesk_tickets_machine/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: /entrypoint.sh

  db:
    image: postgres:9.6.1-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ztm
