version: '2'

services:
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./static:/static
    depends_on:
      - ztm

  ztm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/static
    depends_on:
      - db

  db:
    image: postgres:9.6.1-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ztm
