version: '2'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80
    volumes:
      - ./static:/static
    depends_on:
      - ztm

  ztm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/static
