version: '2'

services:
  app:
    image: prontotools/ztm-app
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-local
    env_file:
      - .env
    ports:
      - 8090:8000
    entrypoint: /entrypoint.sh
